import {
  buildBed,
  buildNightstand,
  buildDresser,
  buildWardrobe,
  buildVanity,
  buildSofa,
  buildArmchair,
  buildCoffeeTable,
  buildSideTable,
  buildTvStand,
  buildOttoman,
  buildDesk,
  buildOfficeChair,
  buildBookshelf,
  buildFilingCabinet,
  buildCeilingPendant,
  buildFloorLamp,
  buildTableLamp,
  buildBedsideLamp,
  buildSconce,
  buildDeskLamp,
  buildCeilingFan,
  buildPainting,
  buildClock,
  buildVase,
  buildSculpture,
  buildRug,
  buildMirror,
  buildDesktop,
  buildLaptop,
  buildMonitor,
  buildKeyboard,
  buildMouse,
  buildTv,
  buildSpeaker,
  buildTallPlant,
  buildMediumPlant,
  buildSucculent,
  buildHangingPlant,
  buildBook,
} from './furniture.js';

export const CATALOG = [
  { id: 'bed', name: 'Platform Bed', category: 'bedroom', build: buildBed },
  { id: 'nightstand', name: 'Nightstand', category: 'bedroom', build: buildNightstand },
  { id: 'dresser', name: 'Dresser', category: 'bedroom', build: buildDresser },
  { id: 'wardrobe', name: 'Wardrobe', category: 'bedroom', build: buildWardrobe },
  { id: 'vanity', name: 'Vanity', category: 'bedroom', build: buildVanity },
  { id: 'sofa', name: 'Sofa', category: 'living', build: buildSofa },
  { id: 'armchair', name: 'Armchair', category: 'living', build: buildArmchair },
  { id: 'coffeeTable', name: 'Coffee Table', category: 'living', build: buildCoffeeTable },
  { id: 'sideTable', name: 'Side Table', category: 'living', build: buildSideTable },
  { id: 'tvStand', name: 'TV Stand', category: 'living', build: buildTvStand },
  { id: 'ottoman', name: 'Ottoman', category: 'living', build: buildOttoman },
  { id: 'desk', name: 'Desk', category: 'office', build: buildDesk },
  { id: 'officeChair', name: 'Office Chair', category: 'office', build: buildOfficeChair },
  { id: 'bookshelf', name: 'Bookshelf', category: 'office', build: buildBookshelf },
  { id: 'filing', name: 'Filing Cabinet', category: 'office', build: buildFilingCabinet },
  { id: 'pendant', name: 'Pendant Light', category: 'lighting', build: buildCeilingPendant },
  { id: 'floorLamp', name: 'Floor Lamp', category: 'lighting', build: buildFloorLamp },
  { id: 'tableLamp', name: 'Table Lamp', category: 'lighting', build: buildTableLamp },
  { id: 'bedsideLamp', name: 'Bedside Lamp', category: 'lighting', build: (m) => buildBedsideLamp(m, 'bedsideL') },
  { id: 'deskLamp', name: 'Desk Lamp', category: 'lighting', build: buildDeskLamp },
  { id: 'sconce', name: 'Wall Sconce', category: 'lighting', build: buildSconce },
  { id: 'ceilingFan', name: 'Ceiling Fan', category: 'lighting', build: buildCeilingFan },
  { id: 'painting', name: 'Painting', category: 'decoration', build: (m) => buildPainting(m) },
  { id: 'clock', name: 'Clock', category: 'decoration', build: buildClock },
  { id: 'vase', name: 'Vase', category: 'decoration', build: buildVase },
  { id: 'sculpture', name: 'Sculpture', category: 'decoration', build: buildSculpture },
  { id: 'rug', name: 'Rug', category: 'decoration', build: buildRug },
  { id: 'mirror', name: 'Mirror', category: 'decoration', build: buildMirror },
  { id: 'book', name: 'Book', category: 'decoration', build: buildBook },
  { id: 'desktop', name: 'Desktop PC', category: 'electronics', build: buildDesktop },
  { id: 'laptop', name: 'Laptop', category: 'electronics', build: buildLaptop },
  { id: 'monitor', name: 'Monitor', category: 'electronics', build: buildMonitor },
  { id: 'keyboard', name: 'Keyboard', category: 'electronics', build: buildKeyboard },
  { id: 'mouse', name: 'Mouse', category: 'electronics', build: buildMouse },
  { id: 'tv', name: 'Television', category: 'electronics', build: buildTv },
  { id: 'speaker', name: 'Speaker', category: 'electronics', build: buildSpeaker },
  { id: 'tallPlant', name: 'Tall Plant', category: 'plants', build: buildTallPlant },
  { id: 'mediumPlant', name: 'Medium Plant', category: 'plants', build: buildMediumPlant },
  { id: 'succulent', name: 'Succulent', category: 'plants', build: buildSucculent },
  { id: 'hangingPlant', name: 'Hanging Plant', category: 'plants', build: buildHangingPlant },
];

export function findCatalog(id) {
  return CATALOG.find((c) => c.id === id) || null;
}
